"""empty message

Revision ID: c931dfc04c43
Revises: f232c1be905e
Create Date: 2021-12-22 15:33:55.152147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c931dfc04c43'
down_revision = 'f232c1be905e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comment', sa.Column('is_delete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Comment', 'is_delete')
    # ### end Alembic commands ###
