"""empty message

Revision ID: f232c1be905e
Revises: 8d0d7bb2a229
Create Date: 2021-12-20 09:13:36.580735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f232c1be905e'
down_revision = '8d0d7bb2a229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Comment") as batch_op:
        batch_op.drop_column("replay_comment_text")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comment', sa.Column('replay_comment_text', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
